--use master
--DROP DATABASE Szkola
--CREATE DATABASE Szkola

use Szkola

CREATE TABLE Przedmioty (
  PrzedmiotID TINYINT IDENTITY(1,1),
  NazwaPrzedmiotu NVARCHAR(50) NOT NULL,
  PRIMARY KEY(PrzedmiotID)
);

CREATE TABLE Profile (
  ProfilID NCHAR(1) NOT NULL,
  NazwaProfilu NVARCHAR(50) NOT NULL,
  PRIMARY KEY(ProfilID)
);

CREATE TABLE OcenyOpis (
  Ocena TINYINT IDENTITY(1,1),
  Nazwa NVARCHAR(15) NOT NULL,
  PRIMARY KEY(Ocena)
);

CREATE TABLE Godziny (
  GodzinaID TINYINT IDENTITY(1,1),
  OdKtorejDoKtorej NVARCHAR(11) NOT NULL,
  PRIMARY KEY(GodzinaID)
);

CREATE TABLE Dzien (
  DzienID TINYINT IDENTITY(1,1),
  NazwaDnia NVARCHAR(12) NOT NULL,
  PRIMARY KEY(DzienID)
);

CREATE TABLE Nauczyciele (
  NauczycielID INTEGER IDENTITY(1,1),
  Imie NVARCHAR(15) NOT NULL,
  Nazwisko NVARCHAR(30) NOT NULL,
  PESEL NVARCHAR(11) NOT NULL,
  DataUrodzenia DATE NOT NULL,
  PRIMARY KEY(NauczycielID)
);

CREATE TABLE Klasy (
  KlasaID TINYINT IDENTITY(1,1),
  NumerKlasy TINYINT NOT NULL,
  ProfilID NCHAR(1) NOT NULL,
  PRIMARY KEY(KlasaID),
  FOREIGN KEY(ProfilID) REFERENCES Profile(ProfilID)
  ON UPDATE CASCADE
);

CREATE TABLE Uczy (
  PrzedmiotID TINYINT NOT NULL,
  NauczycielID INTEGER NOT NULL,
  PRIMARY KEY(PrzedmiotID),
  FOREIGN KEY(PrzedmiotID) REFERENCES Przedmioty(PrzedmiotID),
  FOREIGN KEY(NauczycielID) REFERENCES Nauczyciele(NauczycielID)
  ON UPDATE CASCADE
  ON DELETE CASCADE
);

CREATE TABLE Zajecia (
  DzienID TINYINT NOT NULL,
  GodzinaID TINYINT NOT NULL,
  KlasaID TINYINT NOT NULL,
  PrzedmiotID TINYINT NOT NULL,
  Sala NVARCHAR(3) NOT NULL,
  PRIMARY KEY(DzienID, GodzinaID, Sala),
  FOREIGN KEY(DzienID) REFERENCES Dzien(DzienID),
  FOREIGN KEY(GodzinaID) REFERENCES Godziny(GodzinaID),
  FOREIGN KEY(KlasaID) REFERENCES Klasy(KlasaID)
  ON DELETE CASCADE,
  FOREIGN KEY(PrzedmiotID) REFERENCES Przedmioty(PrzedmiotID)
);

CREATE TABLE Uczniowie (
  UczenID INTEGER IDENTITY(1,1),
  Imie NVARCHAR(15) NOT NULL,
  Nazwisko NVARCHAR(30) NOT NULL,
  KlasaID TINYINT NOT NULL,
  PESEL NVARCHAR(30) NOT NULL,
  DataUrodzenia DATE NOT NULL,
  Ulica NVARCHAR(40) NOT NULL,
  NrDomu TINYINT NOT NULL,
  KodPocztowy NVARCHAR(6) NOT NULL,
  Miejscowosc NVARCHAR(15) NOT NULL,
  PRIMARY KEY(UczenID),
  FOREIGN KEY(KlasaID) REFERENCES Klasy(KlasaID)
);

CREATE TABLE Oceny (
  PrzedmiotID TINYINT NOT NULL,
  UczenID INTEGER NOT NULL,
  Ocena TINYINT NOT NULL,
  Semestr TINYINT NOT NULL,
  PRIMARY KEY(PrzedmiotID, UczenID, Semestr),
  FOREIGN KEY(PrzedmiotID) REFERENCES Przedmioty(PrzedmiotID)
  ON UPDATE CASCADE,
  FOREIGN KEY(UczenID) REFERENCES Uczniowie(UczenID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY(Ocena) REFERENCES OcenyOpis(Ocena)
);

